import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/Components/Navbar/navbar";

const inter = Inter({ subsets: ["latin"] });
const Yekan = localFont({
  src: [
    {
      path: "../public/Font/BYekan+.ttf",
      weight: "700",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR">
      <body dir="rtl" className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
